pipeline {
    agent any
    tools {
         maven 'maven3'
    }
    stages{
        stage('Build'){
            steps{
                 cleanWs()
                 checkout scm
                echo "Building ${env.project1}..."
            }
        }
        
        stage('Upload War To Nexus'){
            steps{
                nexusArtifactUploader artifacts:[
                   [
                        artifactId: 'realestate',
                       classifier: '',
                       file: 'realestate/target/realestate-0.0.1-SNAPSHOT.jar',
                      type: 'jar'
                 ]
             ],
                   credentialsId: 'f132de8e-f9cf-4b2f-a9e3-3c73abfb9fef',
                   groupId: 'torryharrisproject',
                   nexusUrl: '3.133.254.46:8081/',
                   nexusVersion: 'nexus3',
                   protocol: 'http',
                   repository: 'http://3.133.254.46:8081/repository/maven-snapshots/',
                   version: '0.0.1-SNAPSHOT'
  
            }
        }
    }
}
